services:
    formula-backend:
        container_name: formula-backend
        restart: always
        build: .
        ports:
            - 5000:8080
            - 8081:8081
        volumes:
            - ./pb:/pb/pb_data
        networks:
            - network-formula
        # command: go run pb/main.go serve --http=0.0.0.0:8080
        # command: ['/pb/pb_hooks/', 'go run main.go', '--http=0.0.0.0:8080']
        user: 'root'
networks:
    network-formula:
        name: network-bosqo
        external: true
